config-version: 1

# The root folder for the database change scripts
###################### CHANGE TO REPO NAME and SCRIPTS FOLDER NAME
root-folder: '/home/runner/work/ADAM-LAB/ADAM-LAB/sql_scripts/'

# The modules folder for jinja macros and templates to be used across multiple scripts.
modules-folder: null

# Override the default connections.toml file path at snowflake.connector.constants.CONNECTIONS_FILE (OS specific)
###################### CHANGE TO REPO NAME 
connections-file-path: '/home/runner/work/ADAM-LAB/ADAM-LAB/connection.toml'

# Override the default connections.toml connection name. Other connection-related values will override these connection values.
connection-name: 'myconnection'

# Used to override the default name of the change history table (the default is METADATA.SCHEMACHANGE.CHANGE_HISTORY)
######### CHANGE THIS TO YOUR DB & SCHEMA
change-history-table: PSMT_LAKEHOUSE_DEV.DATAOPS_TRAINING1.CHANGE_HISTORY

# Create the change history schema and table, if they do not exist (the default is False)
create-change-history-table: true

# Define values for the variables to replaced in change scripts. vars supplied via the command line will be merged into YAML-supplied vars
vars:
  ######### CHANGE THIS TO YOUR DB & SCHEMA
  sf_database: 'PSMT_LAKEHOUSE_DEV' # The database to which the scripts will be applied
  sf_schema: 'DATAOPS_TRAINING1' # The schema to which the scripts will be applied

# Enable autocommit feature for DML commands (the default is False)
autocommit: false

# Display verbose debugging details during execution (the default is False) 
verbose: true

# Run schemachange in dry run mode (the default is False)
dry-run: false

# A string to include in the QUERY_TAG that is attached to every SQL statement executed
query-tag: 'SCHEMACHANGE-TRAINING'